"use client"

import { useEffect, useRef, useState } from "react"
import Image from "next/image"
import { RiArrowRightLine, RiArrowRightUpLine, RiCheckLine, RiPhoneLine, RiCalendarLine, RiChat3Line, RiShieldCheckLine, RiPlayFill, RiPauseLine, RiMenuLine, RiCloseLine } from "@remixicon/react"
import { Button } from "@/components/ui/button"

const flows = [
  {label:"Un appel décroché",title:"Bonjour, je vous écoute.",text:"Un accueil aux couleurs de votre cabinet, même quand votre équipe est déjà occupée.",bubble:"Bonjour, je souhaiterais un rendez-vous pour un contrôle.",result:"Demande identifiée",icon:RiPhoneLine},
  {label:"Une demande comprise",title:"Les bonnes informations. Au bon moment.",text:"Vos horaires, vos soins et vos consignes guident la conversation. Ce qui demande un avis humain est transmis à l’équipe.",bubble:"Bien sûr. Quel jour vous conviendrait pour ce contrôle ?",result:"Informations recueillies",icon:RiChat3Line},
  {label:"Un suivi organisé",title:"La suite est entre de bonnes mains.",text:"La demande arrive dans votre espace. Votre équipe vérifie le créneau et garde la main sur la confirmation.",bubble:"Votre demande est transmise au cabinet pour confirmation.",result:"À confirmer par le cabinet",icon:RiCalendarLine},
]
const faqs=[
 ["Est-ce que cela remplace mon équipe ?","L’objectif est d’aider votre équipe à gérer l’accueil. Les demandes qui nécessitent une décision, une vérification ou une expertise clinique restent entre ses mains."],
 ["Comment les rendez-vous sont-ils confirmés ?","Une demande n’est pas une réservation. Sans disponibilité et écriture vérifiées dans l’agenda connecté, la demande est transmise à votre équipe pour confirmation."],
 ["Puis-je l’adapter à mon cabinet ?","L’accueil s’appuie sur les informations de votre cabinet : horaires, prestations, langues et consignes. Le paramétrage et les scénarios doivent être validés avant une mise en service."],
 ["Où en est le produit aujourd’hui ?","Standard IA est en phase pilote. L’espace cabinet et les suivis sont disponibles en démonstration. Les connexions aux logiciels dentaires et les conditions de mise en service se valident cabinet par cabinet."],
]

function Action({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Button className={`landing-action ${light?"action-light":""}`} render={<a href={href}/>} nativeButton={false}>{children}<RiArrowRightUpLine className="size-4"/></Button>}
function Bird({size=40}:{size?:number}){return <Image src="/standard-bird.png" alt="" width={size} height={size} className="bird-mark"/>}

export function LandingExperience({appUrl,demoUrl}:{appUrl:string|null;demoUrl:string|null}){
 const [step,setStep]=useState(0)
 const [playing,setPlaying]=useState(false)
 const [menu,setMenu]=useState(false)
 const root=useRef<HTMLDivElement>(null)
 const scene=useRef<HTMLDivElement>(null)
 useEffect(()=>{
  const mq=window.matchMedia("(prefers-reduced-motion: reduce)")
  const update=()=>{if(mq.matches)setPlaying(false)}
  mq.addEventListener("change",update)
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12})
  root.current?.querySelectorAll(".reveal").forEach(el=>observer.observe(el))
  root.current?.classList.add("motion-ready")
  return ()=>{observer.disconnect();mq.removeEventListener("change",update)}
 },[])
 useEffect(()=>{
  if(!playing)return
  const timer=window.setInterval(()=>{if(document.visibilityState==="visible" && scene.current && scene.current.getBoundingClientRect().bottom>0 && scene.current.getBoundingClientRect().top<window.innerHeight)setStep(s=>(s+1)%3)},4200)
  return ()=>window.clearInterval(timer)
 },[playing])
 const flow=flows[step]
 return <div ref={root} className="landing" data-playing={playing}>
  <header className="site-nav wrap"><a href="#top" className="wordmark" aria-label="Standard IA, accueil"><Bird/>Standard<span>IA</span></a><nav className="desktop-nav" aria-label="Navigation principale"><a href="#fonctionnement">Le fonctionnement</a><a href="#cabinet">Votre espace</a><a href="#questions">Questions</a></nav><div className="nav-actions">{appUrl?<a className="login-link" href={appUrl}>Connexion <RiArrowRightUpLine className="size-4"/></a>:<a className="login-link" href="#demo">Réserver une démo <RiArrowRightUpLine className="size-4"/></a>}<Button variant="ghost" size="icon" className="mobile-toggle" aria-label={menu?"Fermer le menu":"Ouvrir le menu"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<RiCloseLine/>:<RiMenuLine/>}</Button></div></header>
  {menu?<nav className="mobile-nav wrap" aria-label="Navigation mobile">{[["#fonctionnement","Le fonctionnement"],["#cabinet","Votre espace"],["#questions","Questions"]].map(([url,label])=><a key={url} href={url} onClick={()=>setMenu(false)}>{label}<RiArrowRightLine className="size-4"/></a>)}</nav>:null}
  <main id="main">
   <section id="top" className="hero wrap">
    <div className="hero-intro"><p className="eyebrow"><span className="tiny-dot"/>L’accueil IA pensé pour les cabinets dentaires</p><h1>Plus de présence.<br/><span>Moins d’interruptions.</span></h1><p className="hero-copy">Un assistant qui accueille vos patients, recueille leurs demandes et prépare la suite. Votre équipe peut se concentrer sur les soins.</p><div className="hero-actions"><Action href="#demo">Réserver une démo</Action><a className="text-link" href="#cabinet">Voir l’espace cabinet <RiArrowRightLine className="size-4"/></a></div><p className="hero-note">Votre accueil. Vos consignes. Votre équipe aux commandes.</p></div>
    <div className="hero-stage" ref={scene} aria-label="Illustration interactive du parcours d’un appel">
     <div className="stage-label"><span className="tiny-dot"/>UNE DEMANDE, UN SUIVI CLAIR<span>EXEMPLE ILLUSTRATIF</span></div>
     <div className="stage-orbit orbit-one"/><div className="stage-orbit orbit-two"/>
     <div className="call-window"><div className="window-top"><span><i/><i/><i/></span><span>ACCUEIL DU CABINET</span></div><div className="call-person"><div className="initials">ML</div><div><strong>Marie L.</strong><span>Nouveau patient · exemple</span></div><RiPhoneLine className="call-icon"/></div><div className="waveform" aria-hidden="true">{Array.from({length:35},(_,i)=><i key={i} style={{height:`${12+(i*17%31)}px`,animationDelay:`${i*-.08}s`}}/>)}</div><div key={step} className="conversation-bubble"><span>{step===0?"LE PATIENT":"STANDARD IA"}</span><p>« {flow.bubble} »</p></div><div className="call-bottom"><span className="tiny-dot"/>Scénario de démonstration<span>FR</span></div></div>
     <div className="assistant-avatar"><Image src="/standard-bird.png" alt="Mascotte Standard IA, un petit oiseau accueillant" width={260} height={260} priority/><div className="avatar-label"><span className="tiny-dot"/>Standard est à l’écoute</div></div>
     <div className="outcome-card" key={`result-${step}`}><span className="outcome-icon"><flow.icon className="size-5"/></span><div><small>LA SUITE, SANS L’OUBLI</small><strong>{flow.result}</strong><span>Contrôle dentaire · Marie L.</span></div><RiCheckLine className="size-4"/></div>
     <div className="stage-controls"><div role="group" aria-label="Étape de la démonstration">{flows.map((f,i)=><button key={f.label} onClick={()=>{setStep(i);setPlaying(false)}} aria-pressed={step===i}><span>0{i+1}</span>{f.label}</button>)}</div><Button variant="ghost" size="icon" aria-label={playing?"Mettre l’animation en pause":"Animer la démonstration"} onClick={()=>setPlaying(!playing)}>{playing?<RiPauseLine/>:<RiPlayFill/>}</Button></div>
    </div>
    <div className="benefit-strip"><span><RiPhoneLine/>Un accueil disponible</span><span><RiChat3Line/>Des demandes structurées</span><span><RiShieldCheckLine/>Une équipe qui garde la main</span></div>
   </section>
   <section className="story-section wrap" id="fonctionnement"><div className="section-intro reveal"><p className="eyebrow">01 / Un accueil qui vous ressemble</p><h2>Le téléphone sonne.<br/>Le cabinet continue.</h2><p>Entre deux patients, les appels s’accumulent. Standard IA transforme chaque demande en une prochaine étape claire.</p></div><div className="flow-grid">{flows.map((f,i)=><article className="flow-item reveal" key={f.label} style={{transitionDelay:`${i*90}ms`}}><div className="flow-number">0{i+1}<f.icon/></div><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
   <section className="workspace-section" id="cabinet"><div className="wrap workspace-grid"><div className="workspace-copy reveal"><p className="eyebrow">02 / Votre poste de pilotage</p><h2>Tout voir.<br/>Savoir quoi faire.</h2><p>Une boîte de réception pour les rappels, les demandes et les situations à vérifier. Chaque suivi trouve un responsable.</p><ul>{["Prioriser les demandes importantes","Attribuer les suivis à votre équipe","Retrouver les informations utiles"].map(x=><li key={x}><RiCheckLine/>{x}</li>)}</ul>{appUrl?<Action href={appUrl}>Ouvrir l’espace cabinet</Action>:<a className="text-link" href="#questions">En savoir plus sur le pilote <RiArrowRightLine className="size-4"/></a>}</div><div className="dashboard-demo reveal"><div className="demo-sidebar"><Bird size={30}/><span className="demo-side-active"><RiChat3Line/></span><RiPhoneLine/><RiCalendarLine/><RiShieldCheckLine/></div><div className="demo-body"><div className="demo-top"><span>Cabinet de démonstration</span><span className="demo-tag">EXEMPLE</span></div><div className="demo-title"><div><small>À FAIRE AUJOURD’HUI</small><h3>Boîte de réception</h3></div><span className="task-count">3</span></div><div className="demo-filter"><span>À traiter <b>3</b></span><span>Résolues</span></div>{[{name:"Marie L.",action:"Demande de contrôle dentaire",tag:"À confirmer",time:"09:42",initial:"ML",color:"mint"},{name:"Thomas B.",action:"Demande de rappel de l’équipe",tag:"Rappel",time:"09:28",initial:"TB",color:"peach"},{name:"Louise D.",action:"Question sur les horaires du cabinet",tag:"À traiter",time:"09:14",initial:"LD",color:"lavender"}].map((row,i)=><div className={`demo-row demo-row-${i}`} key={row.initial}><span className={`mini-avatar ${row.color}`}>{row.initial}</span><div><strong>{row.name}</strong><p>{row.action}</p></div><span className="row-tag">{row.tag}</span><small>{row.time}</small></div>)}<div className="demo-footer"><RiCheckLine/>Les bonnes informations, au même endroit.</div></div><div className="floating-note"><span className="note-avatar">S</span><div><strong>Suivi attribué à Sophie</strong><p>La demande peut avancer.</p></div></div></div></div></section>
   <section className="principles wrap"><div className="section-intro reveal"><p className="eyebrow">03 / À votre rythme</p><h2>Un assistant.<br/>Les règles de votre cabinet.</h2></div><div className="principle-list"><article className="reveal"><span>01</span><div><h3>Il connaît votre accueil.</h3><p>Horaires, prestations, langues et consignes : la conversation part des informations que vous validez.</p></div><RiChat3Line/></article><article className="reveal"><span>02</span><div><h3>Il sait passer la main.</h3><p>Un doute, une demande clinique ou une situation particulière ? La décision revient à votre équipe.</p></div><RiShieldCheckLine/></article><article className="reveal"><span>03</span><div><h3>Il distingue demande et confirmation.</h3><p>Un rendez-vous n’est annoncé comme confirmé qu’après vérification. Sinon, le cabinet reçoit un suivi à traiter.</p></div><RiCalendarLine/></article></div></section>
   <section className="demo-booking wrap" id="demo" aria-labelledby="demo-heading"><div className="reveal"><p className="eyebrow">Faisons connaissance</p><h2 id="demo-heading">Voyez ce que Standard<br/>peut faire pour votre cabinet.</h2><p className="booking-copy">Un échange pour découvrir votre accueil, parcourir l’espace cabinet et voir comment organiser un premier essai ensemble.</p><ul className="booking-points"><li><RiCheckLine/>Une démonstration guidée</li><li><RiCheckLine/>Vos questions, vos cas concrets</li><li><RiCheckLine/>Sans engagement, sans compte à créer</li></ul></div><div className="booking-card reveal"><span className="booking-icon"><RiCalendarLine/></span><h3>Votre prochain accueil<br/>commence par un échange.</h3>{demoUrl?<><p>Choisissez un créneau disponible sur notre calendrier Cal.com. Vous y renseignerez vos coordonnées et recevrez les détails du rendez-vous.</p><Action href={demoUrl}>Choisir mon créneau</Action><small>La réservation se poursuit sur Cal.com.</small></>:<><p>Les réservations de démonstration ouvriront prochainement. Vous pouvez déjà découvrir le fonctionnement de Standard IA.</p><Action href="#fonctionnement">Découvrir le fonctionnement</Action></>}</div></section>
   <section className="faq-section wrap" id="questions"><div className="reveal"><p className="eyebrow">En pratique</p><h2>Quelques réponses,<br/>avant de commencer.</h2></div><div className="faq-list">{faqs.map(([q,a])=><details key={q} className="reveal"><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
   <section className="final-section wrap reveal"><div className="final-panel"><div><p className="eyebrow">Un peu moins de bruit. Un peu plus de soin.</p><h2>Un accueil plus serein<br/>commence ici.</h2><div className="hero-actions"><Action href="#demo" light>Réserver une démo</Action>{appUrl?<a className="text-link" href={appUrl}>Connexion au cabinet <RiArrowRightUpLine className="size-4"/></a>:null}</div></div><div className="final-bird"><Image src="/standard-bird.png" width={270} height={270} alt=""/><span>On s’occupe de l’accueil.</span></div></div></section>
  </main><footer className="wrap site-footer"><a className="wordmark" href="#top"><Bird size={30}/>Standard<span>IA</span></a><p>Pensé pour les équipes dentaires. En phase pilote.</p><a href="#questions">Questions fréquentes <RiArrowRightUpLine className="size-4"/></a></footer>
 </div>
}

