"""Per-call capture for the phone agent: transcript + AI summary + audio recording.

Each call gets a folder: agent/calls/<tenant>/<timestamp>/
  transcript.json  — the conversation (roles + text + tool calls)
  summary.txt      — 3-4 sentence French summary generated by the LLM
  audio.wav        — the full call audio (when recording is enabled)
"""

import json
import os
import wave
from datetime import datetime
from pathlib import Path

CALLS_DIR = Path(__file__).resolve().parent / "calls"

KICKOFF_MARKERS = ("(Démarre la conversation.)", "(Start the conversation.)")


def new_call_dir(tenant_id: str) -> Path:
    ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    d = CALLS_DIR / tenant_id / ts
    d.mkdir(parents=True, exist_ok=True)
    return d


def clean_messages(messages: list[dict]) -> list[dict]:
    """Drop the internal kick-off message; keep the real conversation."""
    out = []
    for m in messages:
        content = m.get("content")
        if isinstance(content, str) and content.startswith(KICKOFF_MARKERS):
            continue
        out.append(m)
    return out


def save_transcript(call_dir: Path, messages: list[dict]) -> None:
    (call_dir / "transcript.json").write_text(
        json.dumps(clean_messages(messages), ensure_ascii=False, indent=2), encoding="utf-8"
    )


def save_summary(call_dir: Path, summary: str) -> None:
    (call_dir / "summary.txt").write_text(summary, encoding="utf-8")


def save_audio(call_dir: Path, audio: bytes, sample_rate: int, num_channels: int) -> None:
    if not audio:
        return
    with wave.open(str(call_dir / "audio.wav"), "wb") as wf:
        wf.setsampwidth(2)
        wf.setnchannels(max(1, num_channels))
        wf.setframerate(sample_rate or 16000)
        wf.writeframes(audio)


def _render_transcript(messages: list[dict]) -> str:
    lines = []
    for m in clean_messages(messages):
        role = m.get("role", "?")
        content = m.get("content")
        if not content and m.get("tool_calls"):
            content = json.dumps(m["tool_calls"], ensure_ascii=False)
        if content:
            lines.append(f"{role}: {content}")
    return "\n".join(lines)[:12000]


def summarize(messages: list[dict]) -> str:
    """Generate a short French after-call summary using the configured LLM."""
    from openai import OpenAI  # local import: only needed at call end

    api_key = os.getenv("OPENAI_API_KEY", "")
    if not api_key:
        return "Résumé indisponible (pas de clé LLM)."
    try:
        client = OpenAI(api_key=api_key, base_url=os.getenv("LLM_BASE_URL") or None)
        transcript = _render_transcript(messages)
        if not transcript.strip():
            return "Appel sans échange verbal."
        resp = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "mistral-small-latest"),
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Tu rédiges un résumé d'appel téléphonique en français, 3-4 phrases : "
                        "qui a appelé, ce qu'il voulait, ce qui a été fait (rendez-vous pris, message), "
                        "et toute action à suivre pour l'équipe."
                    ),
                },
                {"role": "user", "content": "Voici la transcription de l'appel :\n" + transcript},
            ],
            temperature=0.2,
            max_tokens=250,
        )
        return (resp.choices[0].message.content or "Résumé indisponible.").strip()
    except Exception as e:
        return f"Résumé indisponible ({type(e).__name__})."
